export const COLOR_PALETTE_MAIN = '#4540c2';
export const COLOR_PALETTE_SECONDARY = '#099f01';
export const COLOR_PALETTE_FOREGROUND_DARK = '#fff';
export const COLOR_PALETTE_BACKGROUND_DARK = '#0f0f0f';
export const COLOR_PALETTE_BACKGROUND_LIGHT = '#fff';
export const COLOR_PALETTE_FOREGROUND_LIGHT = '#000';
