name: Build Next.js web application
on: push
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pnpm dependencies
        uses: pnpm i
      - name: Build project assets
        run: pnpm run build
